site_name: Navio2 docs
theme_dir: docstheme
site_favicon: favicon.ico
repo_url: https://github.com/emlid/navio2-docs

pages:
- Introduction : 'index.md'
- Navio2 with ArduPilot:
  - 'Hardware setup': 'navio-ardupilot/hardware-setup.md'
  - 'Typical setup schemes': 'navio-ardupilot/typical-setup-schemes.md'
  - 'Raspberry Pi configuration': 'navio-ardupilot/configuring-raspberry-pi.md'
  - 'ArduPilot installation and running' : 'navio-ardupilot/installation-and-running.md'
  - 'Ardupilot upgrade' : 'navio-ardupilot/ardupilot-upgrade.md'
  - 'Ardupilot configuration' : 'navio-ardupilot/ardupilot-tips.md'
  - 'Video streaming': 'navio-ardupilot/video-streaming.md'
  - 'Building ArduPilot from sources': 'navio-ardupilot/building-from-sources.md'
- Navio2 for developers:
  - 'Navio2 examples setup': 'Navio-dev/navio-repository-cloning.md'
  - 'Pinout': 'Navio-dev/pinout.md'
  - '9DOF IMU' : 'Navio-dev/imu-mpu9250_lsm9ds1.md'
  - 'AHRS' : 'Navio-dev/ahrs.md'
  - 'Barometer' : 'Navio-dev/barometer-ms5611.md'
  - 'GPS' : 'Navio-dev/gps-ublox.md'
  - 'GPS via u-center' : 'Navio-dev/gps-ublox-ucenter.md'
  - 'RGB LED' : 'Navio-dev/rgb-led.md'
  - 'PWM output' : 'Navio-dev/pwm-output.md'
  - 'RC input' : 'Navio-dev/rc-input.md'
  - 'RCIO' : 'Navio-dev/rcio.md'
  - 'ADC' : 'Navio-dev/adc.md'
  - 'ROS' : 'Navio-dev/ros.md'
  - 'Wi-Fi Broadcast' : 'Navio-dev/wbc.md'
  - 'Changelogs': 'Navio-dev/changelogs.md'
- Community projects:
  - 'Windows IoT': 'Community-projects/Windows-IoT.md'
  - 'SoftOSD': 'Community-projects/SoftOSD.md'
